name: Deploy to STAGING VPS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGING_VPS_KEY }}

      - name: Deploy to STAGING VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_VPS_USER }}@${{ secrets.STAGING_VPS_HOST }} << 'EOF'
            set -e

            cd /home/ubuntu/repo/web-scrapper

            echo "➡️ Pulling latest code..."
            git fetch origin
            git reset --hard origin/staging

            echo "➡️ Refresh Dependency for Python..."
            pip install -r requirements.txt

            echo "➡️ Restarting service..."
            sudo systemctl restart web-scrapper
          EOF
