name: Deploy Flask to VPS

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e

            cd /home/sendy/repository/web-job-scrapper

            echo "➡️ Pull latest code..."
            git fetch origin
            git reset --hard origin/development

            echo "➡️ Activate virtual environment..."
            source venv/bin/activate

            echo "➡️ Install dependencies..."
            pip install -r requirements.txt

            echo "➡️ Restart Flask service..."
            systemctl restart web-job-scrapper

            echo "✅ Deploy selesai!"
          EOF